# Site settings
#title: Hanuman
title: Matt Huang
tagline: '網路的程式日記'
#description: Hanuman is a minimal yet powerful Jekyll theme for your blogs and websites.
description: This is Record & Diary Blog of WenLiang
cover: assets/images/radhakrishna.jpg
logo: assets/images/logo.png
favicon: assets/images/favicon.png
baseurl: "/WenLiangDailyRecord/"
#baseurl: "/hanuman/" # the subpath of your site, e.g. /blog/ or / for root
url:  "https://wenlianghuang.github.io"
#url: "https://samanyougarg.com" # the base hostname & protocol for your site
mainplain: "2020-02-20(Thur)回診看神內"
pagination:

  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: true

  per_page: 5

# Social
facebook: facebook
twitter: twitter
github:  wenlianghuang/WenLiangDailyRecord

#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate-v2


# Settings for rake task
#20200209 command temporarily
safe: False
lsi: False
#username: samanyougarg #github username
#repo: hanuman #github repository
repo: WenLiangDailyRecord
branch: master #branch
#relative_source: ../hanuman/ #source directory
#destination: ../hanuman-pages/ #destination directory
#production_url:  https://samanyougarg.com/
#source_url:  https://github.com/samanyougarg/hanuman #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml